routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('referral');

Auth::routes(['verify' => true]);

Route::get('/api/top', 'ApiController@top')->name('api.top');
Route::post('/api/order', 'ApiController@order')->name('api.order');
Route::get('/api/account', 'ApiController@account')->name('api.account');

Route::get('/news', 'HomeController@news')->name('news');

Route::put('/home/update', 'HomeController@update')->middleware('auth')->name('profile.update');
Route::get('/code/{code}', 'HomeController@code')->name('profile.code');

Route::group(['middleware' => ['auth','verified']], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/reward', 'ForexController@reward')->name('reward');
    Route::get('/reward/{signal_id}', 'ForexController@reward')->name('reward_select');
    Route::get('/catalog', 'ForexController@catalog')->name('catalog');
    Route::post('/catalog/pay', 'ForexController@catalog_pay')->name('catalog.pay');
    Route::post('/catalog/calc', 'ForexController@catalog_calc')->name('catalog.calc');
    Route::post('/catalog/prolong', 'ForexController@catalog_prolong')->name('catalog.prolong');

    Route::get('/balance', 'ForexController@balance_history')->name('balance');

    Route::get('/withdraw', ['as' => 'withdraw', 'uses' => 'PaymentController@withdraw']);
    Route::post('/withdraw', ['as' => 'withdraw', 'uses' => 'PaymentController@withdraw']);
    Route::post('/payment', ['as' => 'payment', 'uses' => 'PaymentController@payWithpaypal']);
    Route::get('/payment/status',['as' => 'status', 'uses' => 'PaymentController@getPaymentStatus']);
    Route::get('/promo',['as' => 'promo', 'uses' => 'Admin\PromoController@apply', 'namespace' => 'Admin']);

    Route::get('/services', 'ForexController@services')->name('services');

    Route::get('/cart', 'ForexController@cart')->name('cart');
    Route::get('/cart_buy', 'ForexController@cart_buy')->name('cart_buy');
    Route::post('/cart/update', 'ForexController@cart_update')->name('cart_update');

    Route::get('/accounts/list', 'ForexController@accounts')->name('accounts.list');
    Route::get('/accounts/servers/{broker_id}', 'AccountsController@servers')->name('accounts.servers');
    Route::resource('accounts', 'AccountsController');
});

// Route::get('/promo', 'PromoController@apply')->name('promo');

Route::get('/signals/my', 'SignalsController@my')->name('signals.my');
Route::middleware('verified')->prefix('signals')->name('signals.')->group(function () {
    // Route::get('/my', 'SignalsController@my')->name('my');
    Route::get('create', 'SignalsController@create')->name('create');
    Route::post('store', 'SignalsController@store')->name('store');

    Route::get('/account', 'ForexController@signals_account')->name('account');
    Route::delete('', 'ForexController@signals_delete')->name('delete');
    Route::post('/activate', 'ForexController@signals_activate')->name('activate');
    Route::post('/prolong', 'ForexController@signals_prolong')->name('prolong');
});
Route::get('/signals/{id}', 'SignalsController@view')->name('signals.view');

Route::middleware('auth')->group(function () {
    Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('perm:manage-users')->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('signals', 'SignalsController');
        Route::resource('withdraw', 'WithdrawController');
        Route::resource('payments', 'PaymentsController');
        Route::resource('masters', 'MastersController');
        Route::resource('promo', 'PromoController');
        Route::resource('news', 'NewsController');
        Route::get('settings', 'SettingsController@index')->name('settings');
        Route::post('settings', 'SettingsController@index');
        Route::post('settings/upload', 'SettingsController@upload');

        Route::get('tasks', 'TasksController@index')->name('tasks.index');
        Route::delete('tasks/{account_id}', 'TasksController@destroy')->name('tasks.destroy');
    });
});

Route::get('/cron', 'CronController@fx')->name('cron');
Route::get('/cron/notify', 'CronController@notify')->name('notify');

resources/views/balance.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="mb-3">{{ __('Balance History') }}</h3>
                </div>
            </div>
            <table class="table table-striped2 bg-white table-bordered">
                @foreach($transactions as $transaction)
                @if($transaction->amount > 0)
                    <tr class="text-success">
                        <td style="flex: 1" width="100%"><b>{{ __(@$transaction->meta['description'], $transaction->meta) }}</b></td>
                        <td class="text-nowrap">{{ $transaction->created_at->format('d M Y H:i') }}</td>
                        <td class="text-nowrap">+{{ $transaction->amount }} $</td>
                    </tr>
                @elseif($transaction->type == 'withdraw')
                <tr class="">
                    <td style="flex: 1" class="d-flex"><b style="flex: 1">{{ __($transaction->meta['description'], $transaction->meta) }}</b> {!! @$statuses[$transaction->confirmed] !!}</td>
                    <td class="text-nowrap">{{ $transaction->created_at->format('d M Y H:i') }}</td>
                    <td class="text-nowrap">{{ $transaction->amount }} $</td>
                </tr>
                @else
                    <tr class="text-danger">
                        <td style="flex: 1"><b>{{ __($transaction->meta['description'], $transaction->meta) }}</b></td>
                        <td class="text-nowrap">{{ $transaction->created_at->format('d M Y H:i') }}</td>
                        <td class="text-nowrap">{{ $transaction->amount }} $</td>
                    </tr>
                @endif
                @endforeach
            </table>
        </div>
        @include('auth.sidebar')
    </div>
</div>
@endsection

resources/views/cart.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 push-md-4">

            <div class="row mb-3">
                <div class="col-md-12">
                    @if ($method == 'buy')
                        <h3 class="mb-3">{{ __('Buying ' . count($signals) . ' Signal(s)') }}</h3>
                    @else
                        <h3 class="mb-3">{{ __('Prolong ' . count($signals) . ' Signal(s)') }}</h3>
                    @endif
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-12">

                    @include('signals.cart')

                </div>
            </div>
        </div>
        <div class="col-md-4 pull-md-8">
            <div class="row mb-3">
                <div class="col-md-12">
                    <h3 class="mb-3">&nbsp;</h3>
                </div>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                    <dl class="row mb-0">
                        <dt class="col-4">Balance</dt>
                        <dd class="col-8" data-cart="balance">$ <span>{{ Auth::user()->balance }}</span></dd>
                        <dt class="col-4" data-cart="discount" @if (!$discount) style="display: none" @endif>Discount</dt>
                        <dd class="col-8" data-cart="discount" @if (!$discount) style="display: none" @endif>- $ <span>{{ $discount }}</span></dd>
                        <dt class="col-4" data-cart="total">Total</dt>
                        <dd class="col-8" data-cart="total">$ <span>{{ $total }}</span></dd>
                        <dt class="col-4 text-danger" data-cart="shortage" @if (Auth::user()->balance >= $total) style="display: none" @endif>Shortage</dt>
                        <dd class="col-8 text-danger" data-cart="shortage" @if (Auth::user()->balance >= $total) style="display: none" @endif>
                            $ <span>{{ number_format( $total - Auth::user()->balance, 0 ) }}</span>
                            <a href="#" data-toggle="modal" data-target="#exampleModal" class="float-right" data-cart-shortage="{{ $total - Auth::user()->balance }}">{{ __('Top Up Balance') }}</a>
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="card mb-3">
                <!-- <div class="card-header">Payment method</div> -->
                <div class="card-body">
                    @if ($promo)
                    <div class="row mb-0">
                        <dt class="col-4">Promo Code</dt>
                        <dd class="col-8 mb-0">{{ $promo->code }}</dd>
                    </div>
                    @else
                    <form class="promo-form d-flex">
                        <input name="code" type="text" placeholder="Promo Code" class="form-control w-100" required>
                        <button type="submit" class="btn btn-secondary ml-3"><i class="fa fa-check"></i></button>
                    </form>
                    @endif
                </div>
            </div>
            <form class="" action="{{ route('cart_buy') }}" method="get">
                <button href="#" class="btn btn-primary btn-block" data-cart="button" @if ( Auth::user()->balance < $total || !$total ) disabled @endif>{{__('Continue')}} <b>$<span>{{$total}}</span></b></button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/catalog.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-2">
            <div class="row align-items-center">
                @if($is_reward)
                    <div class="col-md-12">
                        <h2 class="mb-0">{{ __('Select Reward') }}</h2>
                        <span class="text-muted mb-3 pl-1">{{ __('You can select any signal on 7 days') }}</span>
                    </div>
                @else
                <div class="col-9">
                    <h2 class="mb-3">{{ __('Catalog') }}</h2>
                </div>
                <div class="col-3">
                    <a href="{{ route('signals.create') }}" class="btn btn-primary" style="float: right"><i class="fa fa-plus fa-fw mr-1"></i> {{ __('Add Signal') }}</a>
                </div>
                @endif
            </div>
        </div>
        <div class="col-md-12">
            @include('errors')
        </div>
        <form method="POST" action="{{ route('catalog.pay') }}" class="col-md-12 push-md-0" id="catalog">
            @csrf
            <div class="card mb-3">
                <div class="card-body pb-0">
                    <table class="w-100 table table-responsive-md text-center catalog-table">
                        <thead>
                            <tr>
                                <th class="text-left">Chart</th>
                                <th>Price</th>
                                <th class="text-left">@sortablelink('name','Name')</th>
                                <th>@sortablelink('growth','Growth')</th>
                                <th>@sortablelink('pips','Pips')</th>
                                <th>@sortablelink('drawdown','DD')</th>
                                <th>@sortablelink('profit_factor','PF')</th>
                                <th>@sortablelink('monthly','Monthly')</th>
                                <th>@sortablelink('daily','Daily')</th>
                                <th>@sortablelink('subscribes_count','Subsrib')</th>
                                <!-- <th>@sortablelink('trades_count','Trades')</th> -->
                                <th>@sortablelink('age','Age')</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($signals as $signal)
                            <tr data-signal="{{$signal->id}}">
                                <td width="150px">
                                    <div class="signal-chart">
                                        <img src="{{$signal->account->chart()}}" alt="">
                                    </div>
                                </td>
                                <td>
                                    <div class="signal-price font-weight-bold hidden">$ {{$signal->price}}</div>
                                    <div class="text-secondary text-nowrap">{{ $signal->expiration_days }} days</div>
                                </td>
                                <td align="left"><a href="{{ route('signals.view', [$signal->id]) }}">{{$signal->name}}</a></td>
                                <td>{{$signal->account->data->growth}}%</td>
                                <td>{{$signal->account->data->pips}}%</td>
                                <td>{{$signal->account->data->drawdown}}</td>
                                <td>{{$signal->account->data->profit_factor}}</td>
                                <td>{{$signal->account->data->monthly}}</td>
                                <td>{{$signal->account->data->daily}}</td>
                                <td>{{$signal->subscribes->count()}}</td>
                                <!-- <td>{{$signal->account->data->trades_count}}</td> -->
                                <td><span class="text-nowrap">{{$signal->account->data->age()}}</span></td>
                                <td>
                                    @if($is_reward)
                                        <a href="{{ route('reward_select', ['signal_id' => $signal->id]) }}" class="btn btn-outline-primary btn-select">{{ __('Select') }}</a>
                                    @else
                                        <input type="checkbox" name="signals[]" value="{{$signal->id}}" hidden>
                                        <button class="btn btn-outline-primary btn-copy">{{ __('Copy') }}</button>
                                    @endif
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                    <div class="text-center">
                        {{ $signals->links() }}
                    </div>
                </div>
            </div>

            @if(!$is_reward)
            <div class="card">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col-md-8">
                            <div class=""><b>Total:</b> <span data-signals="total">0</span>$</div>
                        </div>
                        <div class="col-md-4">
                            <button type="submit" name="button" class="btn btn-primary btn-block" disabled="disabled">Payment</button>
                        </div>
                    </div>
                </div>
            </div>
            @endif
        </form>
        <!-- @include('auth.sidebar') -->
    </div>
</div>

<script type="text/javascript">

</script>

</script>

@endsection

resources/views/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul class="m-0 p-0 pl-3">
            @foreach($errors->all() as $error)
                <li>{!! $error !!}</li>
            @endforeach
        </ul>
    </div>
@endif

@if(Session::has('message'))
<div class="alert alert-success">
  {!! Session::get('message') !!}
</div>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Welcome</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/news.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="mb-3">{{ __('Service News') }}</h3>
                </div>
            </div>
            @foreach($news as $new)
            <div class="card mb-3">
                <div class="card-header font-weight-bold">{{ $new->title }}</div>
                <div class="card-body">
                    <p class="mb-2">{{ $new->content }}</p>
                    <small class="text-muted">{{ $new->created_at->format('d M Y') }}</small>
                </div>
            </div>
            @endforeach
        </div>
        @include('auth.sidebar')
    </div>
</div>
@endsection

resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="mb-3" data-fx-top></div><script src="/js/widget.js"></script>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 push-md-4">
            <h3>&nbsp;</h3>
            @include('errors')
            <div class="card card-body mb-3">{!! $hello !!}</div>
            <div class="card mb-3">
                <div class="card-header">Referral</div>
                <div class="card-body">
                    <div class="row mb-2 align-items-center">
                        <div class="col-md-3">
                            <b2>Your Referral Link:</b2>
                        </div>
                        <div class="col-md-9">
                            <pre class="pre-code mb-0">{{ Auth::user()->getReferralLink() }}</pre>
                        </div>
                    </div>
                    <div class="row mb-2 align-items-center">
                        <div class="col-md-3">
                            <b2>Count Referrals:</b2>
                        </div>
                        <div class="col-md-9">
                            <input type="text" class="form-control-plaintext" value="{{ Auth::user()->referrals()->count() }}" readonly>
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-3">
                            <b2>Profit from referrals:</b2>
                        </div>
                        <div class="col-md-9">
                            <input type="text" class="form-control-plaintext" value="{{ Auth::user()->referralsProfit() }}$" readonly>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mb-3">
                <div class="card-header">Change Password</div>
                <div class="card-body">
                    {{ Form::model(auth()->user(), array('route' => array('profile.update', auth()->user()->id), 'method' => 'PUT')) }}
                    <div class="form-group row align-items-center">
                        <div class="col-md-3">{{ Form::label('password', 'New Password', array('class' => 'mb-0')) }}</div>
                        <div class="col-md-9">{{ Form::text('password', '', array('class' => 'form-control')) }}</div>
                    </div>
                    <div class="form-group row align-items-center">
                        <div class="col-md-3">{{ Form::label('password_confirmation', 'Repeat New Password', array('class' => 'mb-0')) }}</div>
                        <div class="col-md-9">{{ Form::text('password_confirmation', '', array('class' => 'form-control')) }}</div>
                    </div>
                    <div class="form-group row align-items-center">
                        <div class="col-md-3"></div>
                        <div class="col-md-9">{{ Form::submit('Save', array('class' => 'btn btn-primary float-left')) }}</div>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    Latest News
                    <a href="{{ route('news') }}" class="float-right">All</a>
                </div>
                @foreach ($news as $new)
                <div class="card-body">
                    <h6 class="font-weight-bold">{{ $new->title }}</h6>
                    {!! $new->content !!}
                </div>
                @endforeach
            </div>
        </div>
        @include('auth.sidebar')
    </div>
</div>
@endsection

resources/views/services.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 push-md-4">

            @include('signals.expired_onlines')

            @include('signals.expired')

            <div style="clear: both;display: table;"></div>

            @if( empty($expiredSignals) && empty($expiredOnlines) && empty($notexpiredOnlines))
                <div class="card">
                    <div class="card-body">
                        <b>{{ __('You no have expired services.') }}</b>
                    </div>
                </div>
            @endif

        </div>
        @include('auth.sidebar')
    </div>
</div>
@endsection

resources/views/signals.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 push-md-4">

            @include('signals.expired')
            
            @include('signals.deactivated')

            <div style="clear: both;display: table;"></div>

            <h3 class="mb-3">{{ __('My Activated Signals') }}</h3>

            @forelse ($accounts as $account)
                @include('signals.account')
            @empty
                <div class="card">
                    <div class="card-body">
                        <b>{{ __('You no have signals. Go to') }} <a href="{{ route('catalog') }}">{{ ('Catalog') }}</a></b>
                    </div>
                </div>
            @endforelse

        </div>
        @include('auth.sidebar')
    </div>
</div>
@endsection

resources/views/signals_activate.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 push-md-4">
            <h3 class="mb-3">{{ __('Activate Signals') }}</h3>
            <div class="card mb-3">
                <form method="POST" action="{{ route('signals.activate') }}" class="card-body" id="activate">
                    @csrf
                    <div class="row mb-2">
                        <div class="col-md-6">
                            <b>{{ __('Name') }}</b>
                        </div>
                        <div class="col-md-3">
                            <b>{{ __('Expired Date') }}</b>
                        </div>
                        <div class="col-md-3">
                            <b>{{ __('Percent Copy') }}</b>
                        </div>
                    </div>

                    @foreach ($purchases as $purchase)
                    <div class="row mb-2">
                        <div class="col-md-6 mb-2">
                            <input type="text" class="form-control" value="Signal{{$purchase->signal->id}} - {{$purchase->signal->account->data->growth}}% dd-{{$purchase->signal->account->data->drawdown}}%" disabled>
                        </div>
                        <div class="col-md-3 mb-2">
                            <input type="text" class="form-control" value="{{ $purchase->created_at->addDays(15)->format('Y-m-d') }}" disabled>
                        </div>
                        <div class="col-md-3 mb-1">
                            <div class="d-flex">
                                <div class="input-group">
                                    <input type="number" name="purchases[{{ $purchase->id }}]" value="{{ $percent }}" required class="form-control percent-field">
                                    <div class="input-group-append">
                                        <span class="input-group-text">%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endforeach

                    <div class="clearfix" style="clear: both;display: table"></div>

                    <div class="row mt-3">
                        <div class="col-md-4 mt-1">
                            <button type="submit" name="submit" value="1" class="btn btn-success btn-block">{{ __('Activate') }}</button>
                        </div>
                        <div class="col-md-4 mt-1">
                            <select name="account_id" id="account_id" class="form-control" required>
                                <option value="" disabled selected>{{ __('Select account') }}</option>
                                @foreach ($accounts as $account)
                                    <option value="{{$account->id}}">{{$account->login}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-1"></div>
                        <div class="col-md-3 mt-1">
                            <input type="text" readonly class="form-control-plaintext" name="total_percent" id="staticEmail" value="100 / 100" style="padding: 0.375rem 0.75rem;">
                        </div>
                    </div>

                </form>
            </div>
        </div>
        @include('auth.sidebar')
    </div>
</div>
@endsection