routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('referral');

Auth::routes(['verify' => true]);

Route::get('/api/top', 'ApiController@top')->name('api.top');
Route::post('/api/order', 'ApiController@order')->name('api.order');
Route::get('/api/account', 'ApiController@account')->name('api.account');

Route::get('/news', 'HomeController@news')->name('news');

Route::put('/home/update', 'HomeController@update')->middleware('auth')->name('profile.update');
Route::get('/code/{code}', 'HomeController@code')->name('profile.code');

Route::group(['middleware' => ['auth','verified']], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/reward', 'ForexController@reward')->name('reward');
    Route::get('/reward/{signal_id}', 'ForexController@reward')->name('reward_select');
    Route::get('/catalog', 'ForexController@catalog')->name('catalog');
    Route::post('/catalog/pay', 'ForexController@catalog_pay')->name('catalog.pay');
    Route::post('/catalog/calc', 'ForexController@catalog_calc')->name('catalog.calc');
    Route::post('/catalog/prolong', 'ForexController@catalog_prolong')->name('catalog.prolong');

    Route::get('/balance', 'ForexController@balance_history')->name('balance');

    Route::get('/withdraw', ['as' => 'withdraw', 'uses' => 'PaymentController@withdraw']);
    Route::post('/withdraw', ['as' => 'withdraw', 'uses' => 'PaymentController@withdraw']);
    Route::post('/payment', ['as' => 'payment', 'uses' => 'PaymentController@payWithpaypal']);
    Route::get('/payment/status',['as' => 'status', 'uses' => 'PaymentController@getPaymentStatus']);
    Route::get('/promo',['as' => 'promo', 'uses' => 'Admin\PromoController@apply', 'namespace' => 'Admin']);

    Route::get('/services', 'ForexController@services')->name('services');

    Route::get('/cart', 'ForexController@cart')->name('cart');
    Route::get('/cart_buy', 'ForexController@cart_buy')->name('cart_buy');
    Route::post('/cart/update', 'ForexController@cart_update')->name('cart_update');

    Route::get('/accounts/list', 'ForexController@accounts')->name('accounts.list');
    Route::get('/accounts/servers/{broker_id}', 'AccountsController@servers')->name('accounts.servers');
    Route::resource('accounts', 'AccountsController');
});

// Route::get('/promo', 'PromoController@apply')->name('promo');

Route::get('/signals/my', 'SignalsController@my')->name('signals.my');
Route::middleware('verified')->prefix('signals')->name('signals.')->group(function () {
    // Route::get('/my', 'SignalsController@my')->name('my');
    Route::get('create', 'SignalsController@create')->name('create');
    Route::post('store', 'SignalsController@store')->name('store');

    Route::get('/account', 'ForexController@signals_account')->name('account');
    Route::delete('', 'ForexController@signals_delete')->name('delete');
    Route::post('/activate', 'ForexController@signals_activate')->name('activate');
    Route::post('/prolong', 'ForexController@signals_prolong')->name('prolong');
});
Route::get('/signals/{id}', 'SignalsController@view')->name('signals.view');

Route::middleware('auth')->group(function () {
    Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('perm:manage-users')->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('signals', 'SignalsController');
        Route::resource('withdraw', 'WithdrawController');
        Route::resource('payments', 'PaymentsController');
        Route::resource('masters', 'MastersController');
        Route::resource('promo', 'PromoController');
        Route::resource('news', 'NewsController');
        Route::get('settings', 'SettingsController@index')->name('settings');
        Route::post('settings', 'SettingsController@index');
        Route::post('settings/upload', 'SettingsController@upload');

        Route::get('tasks', 'TasksController@index')->name('tasks.index');
        Route::delete('tasks/{account_id}', 'TasksController@destroy')->name('tasks.destroy');
    });
});

Route::get('/cron', 'CronController@fx')->name('cron');
Route::get('/cron/notify', 'CronController@notify')->name('notify');

app/Http/Controllers/Admin/PaymentsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

use App\Http\Controllers\Controller;

use Bavix\Wallet\Models\Transaction;

class PaymentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $aTransactions = Transaction::where([
            'type' => 'buy',
        ])->orderBy('id', 'desc');
        $transactions = $aTransactions->paginate(20);
        $transactionsSum = $aTransactions->sum('amount');
        return view('admin.payments.index')->with([
            'transactions' => $transactions,
            'transactions_sum' => $transactionsSum,
            'statuses' => [
                '<span class="text-muted">Waiting...</span>',
                '<span class="text-success">Accepted</span>',
                '<span class="text-danger">Declined</span>',
            ],
        ]);
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Http\ReferralHelper;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use PayPal\Rest\ApiContext;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Api\Agreement;
use PayPal\Api\Payer;
use PayPal\Api\Plan;
use PayPal\Api\PaymentDefinition;
use PayPal\Api\PayerInfo;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Amount;
use PayPal\Api\Transaction;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Payment;
use PayPal\Api\PaymentExecution;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;
use URL;

class PaymentController extends Controller
{
    public function __construct()
    {
         /** PayPal api context **/
         $paypal_conf = config('paypal');
         $this->_api_context = new ApiContext(new OAuthTokenCredential(
             $paypal_conf['client_id'],
             $paypal_conf['secret'])
         );
         $this->_api_context->setConfig($paypal_conf['settings']);
    }

    public function payWithpaypal(Request $request)
    {
      $amountToBePaid = $request->get('amountToBePaid');
      $payer = new Payer();
      $payer->setPaymentMethod('paypal');

      $item_1 = new Item();
      $item_1->setName(__('User Balance') . ' ' . Auth::user()->id ) /** название элемента **/
              ->setCurrency('USD')
              ->setQuantity(1)
              ->setPrice($amountToBePaid); /** цена **/

      $item_list = new ItemList();
      $item_list->setItems(array($item_1));

      $amount = new Amount();
      $amount->setCurrency('USD')
             ->setTotal($amountToBePaid);

      $redirect_urls = new RedirectUrls();
      /** Укажите обратный URL **/
      $redirect_urls->setReturnUrl(URL::route('status'))
                ->setCancelUrl(URL::route('status'));

      $transaction = new Transaction();
      $transaction->setAmount($amount)
              ->setItemList($item_list)
              ->setDescription('Описание транзакции');

      $payment = new Payment();
      $payment->setIntent('Sale')
              ->setPayer($payer)
              ->setRedirectUrls($redirect_urls)
              ->setTransactions(array($transaction));
      try {
           $payment->create($this->_api_context);
      } catch (\PayPal\Exception\PPConnectionException $ex) {
           if (\Config::get('app.debug')) {
              \Session::put('error', 'Таймаут соединения');
              return Redirect::route('/');
           } else {
              \Session::put('error', 'Возникла ошибка, извините за неудобство');
              return Redirect::route('/');
           }
      }

      foreach ($payment->getLinks() as $link) {
        if ($link->getRel() == 'approval_url') {
           $redirect_url = $link->getHref();
           break;
        }
      }

      /** добавляем ID платежа в сессию **/
      \Session::put('paypal_payment_id', $payment->getId());

      if (isset($redirect_url)) {
         /** редиректим в paypal **/
         return Redirect::away($redirect_url);
      }

      \Session::put('error', 'Произошла неизвестная ошибка');
      return Redirect::route('/');
    }

    public function getPaymentStatus(Request $request)
    {
      /** Получаем ID платежа до очистки сессии **/
      $payment_id = Session::get('paypal_payment_id');
      if(!$payment_id)
        $payment_id = $request->get('paymentId');
      /** Очищаем ID платежа **/
      Session::forget('paypal_payment_id');

      if (empty($request->PayerID) || empty($request->token)) {
         session()->flash('error', 'Payment failed');
         return Redirect::route('/');
      }

      $payment = Payment::get($payment_id, $this->_api_context);
      $execution = new PaymentExecution();
      $execution->setPayerId($request->PayerID);

      /** Выполняем платёж **/
      try{
          $result = $payment->execute($execution, $this->_api_context);
      }catch(PayPalConnectionException $e){
          dd($e->getBody());
      }

      if ($result->getState() == 'approved') {
         session()->flash('success', 'Платеж прошел успешно');
         // dd($result);
         // dd($result->transactions[0]->item_list->items[0]);
         $sum = $result->transactions[0]->item_list->items[0]->price;
         $name = $result->transactions[0]->item_list->items[0]->name;
         // $user_id = explode('#', $name)[1];
         // ReferralHelper::bonus($sum);
         Auth::user()->deposit($sum, 'paypal', ['description' => 'Deposit with Paypal']);
         ReferralHelper::reward_event('replenishment');
         return Redirect::route('cart');
      }

      session()->flash('error', 'Платеж не прошел');
      return Redirect::route('/');
    }

    function withdraw(Request $request) {
        if($request->get('sum')) {
            $transaction = @Auth::user()->withdraw($request->get('sum'), [
                'description' => __('Withdraw :sum$', ['sum' => $request->get('sum')]),
                'requisites' => \nl2br($request->get('requisites'))
            ], false);

            if($transaction) {
                $message = __('<b>Your request has been successfully sent.</b> You can track the status of your request on the <a href="/balance">balance history page</a>. Approval takes up to 3 days.');
                Session::flash('message', $message);
                return Redirect::to(route('home'))->with('message', $message);
            }
        }
        return view('payment.withdraw')->with([

        ]);
    }
}

resources/views/admin/payments/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 push-md-0">
            <div class="row">
                <div class="col-9">
                    <h2 class="mb-3">Payments Journal</h2>
                </div>
                <!-- <div class="col-3">
                    <a href="{{ route('admin.users.create') }}" class="btn btn-primary" style="float: right">Create</a>
                </div> -->
            </div>
            <table class="table table-striped bg-white table-bordered">
                <thead>
                    <tr>
                        <!-- <td>ID</td> -->
                        <td>Date</td>
                        <td>User</td>
                        <td>Signals</td>
                        <td>Price</td>
                        <td>Comission</td>
                        <!-- <td></td> -->
                    </tr>
                </thead>
                <tbody>
                @foreach($transactions as $key => $value)
                    <tr>
                        <!-- <td>{{ $value->id }}</td> -->
                        <td width="160px">{{ $value->created_at->format('d M Y H:i') }}</td>
                        <td><a href="/admin/users/{{ $value->wallet->holder->id }}/edit" target="_blank">{{ $value->wallet->holder->name }}</a></td>
                        <td>{!! @$value->meta['signals'] !!}</td>
                        <td>{!! abs($value->amount) !!}$</td>
                        <td>{!! @$value->meta['comission'] !!}$</td>

                        <td style="white-space: nowrap">
                            {{ Form::open(array('url' => 'admin/transactions/' . $value->id, 'class' => 'float-right')) }}
                                {{ Form::hidden('_method', 'DELETE') }}
                                <!-- <button class="btn btn-sm btn-danger float-right ml-1" type="submit" value="1"><i class="fas fa-fw fa-trash-alt"></i></button> -->
                            {{ Form::close() }}
                            @if ($value->confirmed == 0)
                            {{ Form::open(array('url' => 'admin/transactions/' . $value->id, 'class' => 'float-right')) }}
                                {{ Form::hidden('_method', 'PATCH') }}
                                <!-- <button class="btn btn-sm btn-danger float-right ml-1" type="submit" name="confirmed" value="2"><i class="fas fa-fw fa-times"></i></button> -->
                                <!-- <button class="btn btn-sm btn-success float-right ml-1" type="submit" name="confirmed" value="1" @if($value->wallet->holder->transactionsalAvailable() < abs($value->amount)) disabled @endif><i class="fas fa-fw fa-check"></i></button> -->
                            {{ Form::close() }}
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {{ $transactions->links() }}
        </div>
        <div class="col-md-3 pull-md-9">

        </div>
    </div>
</div>
@endsection