routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('referral');

Auth::routes(['verify' => true]);

Route::get('/api/top', 'ApiController@top')->name('api.top');
Route::post('/api/order', 'ApiController@order')->name('api.order');
Route::get('/api/account', 'ApiController@account')->name('api.account');

Route::get('/news', 'HomeController@news')->name('news');

Route::put('/home/update', 'HomeController@update')->middleware('auth')->name('profile.update');
Route::get('/code/{code}', 'HomeController@code')->name('profile.code');

Route::group(['middleware' => ['auth','verified']], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/reward', 'ForexController@reward')->name('reward');
    Route::get('/reward/{signal_id}', 'ForexController@reward')->name('reward_select');
    Route::get('/catalog', 'ForexController@catalog')->name('catalog');
    Route::post('/catalog/pay', 'ForexController@catalog_pay')->name('catalog.pay');
    Route::post('/catalog/calc', 'ForexController@catalog_calc')->name('catalog.calc');
    Route::post('/catalog/prolong', 'ForexController@catalog_prolong')->name('catalog.prolong');

    Route::get('/balance', 'ForexController@balance_history')->name('balance');

    Route::get('/withdraw', ['as' => 'withdraw', 'uses' => 'PaymentController@withdraw']);
    Route::post('/withdraw', ['as' => 'withdraw', 'uses' => 'PaymentController@withdraw']);
    Route::post('/payment', ['as' => 'payment', 'uses' => 'PaymentController@payWithpaypal']);
    Route::get('/payment/status',['as' => 'status', 'uses' => 'PaymentController@getPaymentStatus']);
    Route::get('/promo',['as' => 'promo', 'uses' => 'Admin\PromoController@apply', 'namespace' => 'Admin']);

    Route::get('/services', 'ForexController@services')->name('services');

    Route::get('/cart', 'ForexController@cart')->name('cart');
    Route::get('/cart_buy', 'ForexController@cart_buy')->name('cart_buy');
    Route::post('/cart/update', 'ForexController@cart_update')->name('cart_update');

    Route::get('/accounts/list', 'ForexController@accounts')->name('accounts.list');
    Route::get('/accounts/servers/{broker_id}', 'AccountsController@servers')->name('accounts.servers');
    Route::resource('accounts', 'AccountsController');
});

// Route::get('/promo', 'PromoController@apply')->name('promo');

Route::get('/signals/my', 'SignalsController@my')->name('signals.my');
Route::middleware('verified')->prefix('signals')->name('signals.')->group(function () {
    // Route::get('/my', 'SignalsController@my')->name('my');
    Route::get('create', 'SignalsController@create')->name('create');
    Route::post('store', 'SignalsController@store')->name('store');

    Route::get('/account', 'ForexController@signals_account')->name('account');
    Route::delete('', 'ForexController@signals_delete')->name('delete');
    Route::post('/activate', 'ForexController@signals_activate')->name('activate');
    Route::post('/prolong', 'ForexController@signals_prolong')->name('prolong');
});
Route::get('/signals/{id}', 'SignalsController@view')->name('signals.view');

Route::middleware('auth')->group(function () {
    Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('perm:manage-users')->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('signals', 'SignalsController');
        Route::resource('withdraw', 'WithdrawController');
        Route::resource('payments', 'PaymentsController');
        Route::resource('masters', 'MastersController');
        Route::resource('promo', 'PromoController');
        Route::resource('news', 'NewsController');
        Route::get('settings', 'SettingsController@index')->name('settings');
        Route::post('settings', 'SettingsController@index');
        Route::post('settings/upload', 'SettingsController@upload');

        Route::get('tasks', 'TasksController@index')->name('tasks.index');
        Route::delete('tasks/{account_id}', 'TasksController@destroy')->name('tasks.destroy');
    });
});

Route::get('/cron', 'CronController@fx')->name('cron');
Route::get('/cron/notify', 'CronController@notify')->name('notify');

app/Signal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Signal extends Model
{
    use Sortable;

    private $column;
    private $direction;
    protected $guarded = [];

    public function __construct($column = 'signals.id', $direction = 'asc')
    {
        $this->column = $column;
        $this->direction = $direction;
    }

    function growth() {
        return $this->account->data->growth;
    }

    function account(){
        return $this->belongsTo('App\Account');
    }

    function subscribes(){
        return $this->hasMany('App\Purchase');
    }

    function subscribes_count() {
        return $this->subscribes->count();
    }

    function user(){
        return $this->account->belongsTo('App\User');
    }

    function marks(){
        // <!-- Rank #422, Real, USD, Forex Cheaf -->
        $marks = array();

        $marks[] = $this->is_demo ? 'Demo' : 'Real';
        $marks[] = strtoupper($this->account->currency);
        $marks[] = $this->account->data->server;

        return implode(', ', $marks);
    }
}

app/Http/Controllers/Admin/SignalsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

use App\Http\Controllers\Controller;

use App\Http\Myfxbook;

use App\Account;

use App\Signal;

class SignalsController extends Controller
{
    public function index()
    {
        $signals = Signal::orderBy('id', 'desc')->paginate(10);
        return view('admin.signals.index')->with([
            'signals' => $signals,
            'statuses' => [
                '<span class="text-muted">Waiting</span>',
                '<span class="text-success">Accepted</span>',
                '<span class="text-danger">Declined</span>',
            ],
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Signal  $signal
     * @return \Illuminate\Http\Response
     */
    public function destroy(Signal $signal)
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        $signal = Signal::find($signal)->first();
        $signal->delete();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // redirect
        Session::flash('message', 'Successfully deleted the signal!');
        return Redirect::to('admin/signals');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Signal $signal)
    {
        // show the edit form and pass the nerd
        return view('admin.signals.edit')
            ->with('signal', $signal);
    }

    function update(Request $request, Signal $signal) {

        $rules = array(
            // 'myfxbook_email' => 'required',
            // 'myfxbook_password' => 'required',
        );
        $validator = Validator::make($request->all(), $rules);

        $data = [
            'status' => $request->status
        ];
        if($request->get('name')){
            $data['name'] = $request->get('name');
            $data['description'] = $request->get('description');
            $data['price'] = $request->get('price');
            $data['expiration_days'] = $request->get('expiration_days');
        }
        if($request->get('myfxbook_email')) {
            $token = Myfxbook::login($request->get('myfxbook_email'), $request->get('myfxbook_password'));

            $myfxbook_error = false;
            if(empty($token)) {
                $myfxbook_error = true;
            }else{
                $account = $signal->account;
                $accountInfo = Myfxbook::getAccountInfo($token, $account->login);
                $accountHistory = [];

                if(!$accountInfo){
                    $myfxbook_error = true;
                }else{
                    $accountHistory = Myfxbook::getAccountHistory($token, $accountInfo->id);
                }
            }

            if ($myfxbook_error) {
                if($myfxbook_error) {
                    $validator->errors()->add('myfxbook_email', 'Myfxbook account not found');
                    $validator->getMessageBag()->add('myfxbook_email', 'Myfxbook account not found');
                }
                return Redirect::to("admin/signals/{$signal->id}/edit/" )
                    ->withErrors($validator->errors())
                    ->withInput($request->all());
            }

            $account->setData($token, $accountInfo, $accountHistory);
        }
        $signal->update($data);
        return Redirect::to('admin/signals');
    }
}

app/Http/Controllers/SignalsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

use App\Signal;

use App\Http\Myfxbook;

class SignalsController extends Controller
{
    function __construct() {
        // $this->middleware('auth');
    }

    function view(Request $request, $id){
        $signal = Signal::find($id);

        if(!$signal || !$signal->account->data) {
            abort(404);
        }

        if($signal['status'] != 1 && $signal->account->user_id != Auth::user()->id){
            abort(404);
        }

        Signal::where('id', '=', $id)->increment('views_count', 1);

        return view('signals.view')->with('signal', $signal);
    }

    function my(Request $request) {
        $transactions = Auth::user()->transactions()->where('type', '=', 'earned')->get();
        $signals = Signal::leftJoin('accounts', 'signals.account_id', '=', 'accounts.id')
            ->select('signals.*')
            ->where('accounts.user_id', '=',  Auth::user()->id)->get();

        foreach($signals as $key => $signal) {
            $signals[$key]->total = $this->_find($transactions, $signal->id);
        }

        return view('signals.my')->with([
            'signals' => $signals,
            'statuses' => [
                '<span class="text-muted">Waiting</span>',
                '<span class="text-success">Accepted</span>',
                '<span class="text-danger">Declined</span>',
            ],
        ]);
    }

    function _find($transactions, $signal_id) {
        $sum = 0;
        foreach($transactions as $transaction) {
            if($transaction->meta['signal_id'] == $signal_id) $sum += $transaction->amount;
        }
        return $sum;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $accounts = Auth::user()->accounts;
        return view('signals.create')->with([
            'accounts' => $accounts
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = array(
            'name' => 'required',
            'description' => 'required',
            'price' => 'required|integer',
            'expiration_days' => 'required|integer',
            'account_id' => 'required|integer',
            'invest_password' => 'required',
            // 'myfxbook_email' => 'required',
            // 'myfxbook_password' => 'required',
        );
        $validator = Validator::make($request->all(), $rules);


        // $token = "lcZXl2EJUmEqPI2RBD6a543814";

        $myfxbook_error = false;


        // process the code
        if ($validator->fails() || $myfxbook_error) {
            if($myfxbook_error) {
                $validator->errors()->add('myfxbook_email', 'Myfxbook account not found');
                $validator->getMessageBag()->add('myfxbook_email', 'Myfxbook account not found');
            }
            return Redirect::to('signals/create')
                ->withErrors($validator->errors())
                ->withInput($request->all());
        } else {

            $signal = new Signal;
            $signal->name = $request->get('name');
            $signal->description = $request->get('description');
            $signal->price = (int) $request->get('price');
            $signal->expiration_days = (int) $request->get('expiration_days');
            $signal->account_id = $request->get('account_id');
            $signal->invest_password = $request->get('invest_password');
            $signal->save();

            // redirect
            Session::flash('message', 'Successfully submited request!');
            return Redirect::to('signals/my')->with('message', 'Successfully submited request!');
        }
    }
}

resources/views/signals/account.blade.php
@if ($account->subscribes->count() > 0)
<form class="card mb-3" data-account="{{$account->id}}" data-edit="{{intVal($is_edit)}}">
    <div class="card-header d-flex align-items-center">
        <span>Account {{$account->login}}</span>
        <div style="flex: 1"></div>
        @if ($account->percentSum() < 100)
            <button class="btn btn-light btn-sm" disabled>Free Percents - {{ 100 - $account->percentSum() }}%</button>
        @endif
        @if($is_edit != "false")
            <button type="button" class="btn btn-success ml-3 btn-sm" data-toggle-edit="{{$account->id}}" name="submit">
                <i class="fas fa-fw fa-check"></i>
            </button>
        @else
            <button type="button" class="btn btn-primary ml-3 btn-sm" data-toggle-edit="{{$account->id}}" name="submit">
                <i class="fas fa-fw fa-pencil-alt"></i>
            </button>
        @endif
        </button>
    </div>

    <div class="card-body">
        <div class="row mb-2">
            <div class="col-md-4">
                <b>{{ __('Name') }}</b>
            </div>
            <div class="col-md-3">
                <b>{{ __('Expired Date') }}</b>
            </div>
            <div class="col-md-5">
                <b>{{ __('Percent Copy') }}</b>
            </div>
        </div>

        @foreach ($account->subscribes as $subscribe)
        <div class="row mb-3">
            <div class="col-md-4 mb-2">
                <input type="text" class="form-control" value="{{$subscribe->signal->name}} - {{$subscribe->signal->account->data->growth}}% dd-{{$subscribe->signal->account->data->drawdown}}%" disabled>
            </div>
            <div class="col-md-3 mb-2">
                <input type="text" class="form-control" value="{{ $subscribe->expiredDate()->format('Y-m-d') }}" disabled>
            </div>
            <div class="col-md-5 mb-2">
                <div class="d-flex">
                    <div class="input-group">
                        <input type="number" value="{{ $subscribe->percent }}" name="signals[{{$subscribe->id}}]" @if(!$is_edit) disabled @endif class="form-control percent-field">
                        <div class="input-group-append">
                            <span class="input-group-text">%</span>
                        </div>
                    </div>
                    <button class="btn btn-primary ml-4" data-prolong="{{ $subscribe->id }}" type="button" data-toggle="tooltip" data-placement="top" title="{{ __('Prolong') }}"><i class="far fa-fw fa-calendar-plus"></i></button>
                    <button class="btn btn-danger ml-2" data-remove="{{ $subscribe->id }}"><i class="fas fa-fw fa-times"></i></button>
                </div>
            </div>
        </div>
        @endforeach

        @if ($is_edit)
            <div style="clear: both;display: table;"></div>
            <div class="row mt-2">
                <div class="col-md-4 mt-1">
                    <select name="purchase_id" id="purchase_id" class="form-control" required>
                        <option value="" disabled selected>Add signal</option>
                        @foreach ($unusedSignals as $subscribe)
                            <option value="{{$subscribe->id}}">{{$subscribe->signal->name}} - {{$subscribe->signal->account->data->growth}}% dd-{{$subscribe->signal->account->data->drawdown}}%</option>
                        @endforeach
                    </select>
                    @csrf
                </div>
                <div class="col-md-2 mt-1">
                    <button type="submit" name="add_signal" value="1" class="btn btn-success btn-block"><i class="fas fa-plus"></i></button>
                </div>
                <div class="col-md-1 mt-1">

                </div>
                <div class="col-md-5 mt-1">
                    <input type="text" readonly class="form-control-plaintext" name="total_percent" id="staticEmail" value="100 / 100" style="padding: 0.375rem 0.75rem;">
                </div>
            </div>
        @endif

    </div>
</form>
@endif

resources/views/signals/cart.blade.php
<div class="card mb-3">
    <div class="card-body">
        <table class="w-100 table table-responsive-md text-center catalog-table">
            <thead>
                <tr>
                    <th class="text-left">Chart</th>
                    <th>Price</th>
                    <th class="text-left">Name</th>
                    <!-- <th>Growth</th>
                    <th>Pips</th>
                    <th>DD</th>
                    <th>PF</th> -->
                    <!-- <th>Monthly</th>
                    <th>Daily</th>
                    <th>Subsrib</th>
                    <th>Trades</th>
                    <th>Age</th> -->
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach($signals as $key => $signal)
                <tr data-signal="{{$signal->id}}" data-pushace="{{$signal->purchase_id}}">
                    <td width="150px">
                        <div class="signal-chart">
                            <img src="{{$signal->account->chart()}}" alt="">
                        </div>
                    </td>
                    <td>
                        <div class="signal-price font-weight-bold hidden">$ {{$signal->price}}</div>
                        <div class="text-secondary text-nowrap">{{ $signal->expiration_days }} days</div>
                    </td>
                    <td align="left"><a href="{{ route('signals.view', [$signal->id]) }}">{{$signal->name}}</a></td>
                    <!-- <td>{{$signal->account->data->growth}}%</td>
                    <td>{{$signal->account->data->pips}}%</td>
                    <td>{{$signal->account->data->drawdown}}</td>
                    <td>{{$signal->account->data->profit_factor}}</td> -->
                    <!-- <td>{{$signal->account->data->monthly}}</td>
                    <td>{{$signal->account->data->daily}}</td>
                    <td>{{$signal->subscribes->count()}}</td>
                    <td>{{$signal->account->data->trades_count}}</td>
                    <td><span class="text-nowrap">{{$signal->account->data->age()}}</span></td> -->
                    <td class="text-right">
                        @if ($method == 'buy')
                        <button class="btn btn-default btn-remove float-right"><i class="fa fa-times"></i></button>
                        <div class="d-inline-block float-right">
                            <div class="input-group">
                              <span class="input-group-btn">
                                  <button type="button" class="btn btn-default btn-number" data-type="minus" data-field="quant[{{$key}}]" @if($signal->quantity < 2) disabled="disabled" @endif>
                                      <span class="fa fa-minus"></span>
                                  </button>
                              </span>
                              <input type="text" style="max-width: 50px" name="quant[{{$key}}]" class="form-control input-number" value="{{$signal->quantity}}" min="1" max="10">
                              <span class="input-group-btn">
                                  <button type="button" class="btn btn-default btn-number" data-type="plus" data-field="quant[{{$key}}]">
                                      <span class="fa fa-plus"></span>
                                  </button>
                              </span>
                            </div>
                        </div>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/signals/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="mb-3">{{ __('Add Signal') }}</h3>
                </div>
            </div>

            @include('errors')

            {{ Form::open(array('url' => 'signals/store')) }}
            <div class="card mb-3">
                <!-- <div class="card-header font-weight-bold"></div> -->
                <div class="card-body">
                    <div class="form-group row align-items-center">
                        <div class="col-md-3">{{ Form::label('name', __('Name'), array('class' => 'mb-0')) }}</div>
                        <div class="col-md-9">{{ Form::text('name', '', array('class' => 'form-control')) }}</div>
                    </div>
                    <div class="form-group row align-items-center">
                        <div class="col-md-3">{{ Form::label('description', __('Description'), array('class' => 'mb-0')) }}</div>
                        <div class="col-md-9">{{ Form::textarea('description', '', array('class' => 'form-control', 'rows' => 4)) }}</div>
                    </div>

                    <hr>

                    <div class="form-group row">
                        <div class="col-md-3">{{ Form::label('price', __('Price'), array('class' => 'mb-0 col-form-label')) }}</div>
                        <div class="col-md-9">
                            <div class="input-group">
                                {{ Form::text('price', 10, array('class' => 'form-control', 'pattern' => '[0-9]+')) }}
                                <div class="input-group-append">
                                    <span class="input-group-text">USD</span>
                                </div>
                            </div>
                            <small class="form-text text-muted">{!! __('<b>Attention!</b> The service takes a commission of :percent% for each purchase of your signal from the price you specified in the "Price" field', ['percent' => env('COMISSION_PERCENT')]) !!}</small>
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <div class="col-md-3">{{ Form::label('expiration_days', __('Expiration Days'), array('class' => 'mb-0')) }}</div>
                        <div class="col-md-9">{{ Form::text('expiration_days', 30, array('class' => 'form-control', 'pattern' => '[0-9]+')) }}</div>
                    </div>

                    <hr>

                    <div class="form-group row align-items-center">
                        <div class="col-md-3">{{ Form::label('account_id', __('Account'), array('class' => 'mb-0')) }}</div>
                        <div class="col-md-9">
                            <select name="account_id" id="account_id" class="form-control" required>
                                <option value="" disabled selected>{{ __('Select account') }}</option>
                                @foreach ($accounts as $account)
                                    <option value="{{$account->id}}">{{$account->login}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-3">{{ Form::label('invest_password', __('Invest Password'), array('class' => 'mb-0 col-form-label')) }}</div>
                        <div class="col-md-9">
                            {{ Form::text('invest_password', '', array('class' => 'form-control', 'required' => 'required')) }}
                            <small class="form-text text-muted">{{ __('Please enter your investment password for your account, this is necessary to update financial statistics.') }}</small>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9">
                            <button type="submit" class="btn btn-primary">{{ __('Submit Request') }}</button>
                        </div>
                    </div>
                </div>
            </div>
            {{ Form::close() }}
        </div>
        @include('auth.sidebar')
    </div>
</div>
@endsection

resources/views/signals/deactivated.blade.php
<div id="deactivatedSignals">
    @if ($deactivatedSignals->count() > 0)
    <h3 class="mb-3">My Deactivated Signals <span class="badge badge-danger">{{$deactivatedSignals->count()}}</span></h3>
    <div class="card mb-4">
        <form method="POST" action="{{ route('signals.activate') }}" class="card-body">
            @csrf
            <div class="row mb-2">
                <div class="col-md-8">
                    <b>{{ __('Name') }}</b>
                </div>
                <div class="col-md-3">
                    <b>{{ __('Expired Date') }}</b>
                </div>
                <div class="col-md-1"></div>
            </div>

            @foreach ($deactivatedSignals as $purchase)
            <div class="row mb-3 align-items-center">
                <div class="col-md-8 mb-2">
                    <input type="text" class="form-control" value="{{$purchase->signal->name}} - {{$purchase->signal->account->data->growth}}% dd-{{$purchase->signal->account->data->drawdown}}%" disabled>
                </div>
                <div class="col-md-3 mb-2">
                    <input type="text" class="form-control" value="{{ $purchase->expiredDate()->format('Y-m-d') }}" disabled>
                </div>
                <div class="col-md-1 mb-2">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck{{ $purchase->id }}" name="purchases[]" value="{{ $purchase->id }}">
                        <label class="custom-control-label" for="customCheck{{ $purchase->id }}"></label>
                    </div>
                </div>
            </div>
            @endforeach

            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-success" type="submit" name="submit" value="1" disabled>Activate Signals</button>
                </div>
            </div>
        </form>
    </div>
    @endif
</div>

resources/views/signals/expired.blade.php
<div id="expiredSignals">
    @if ($expiredSignals->count() > 0)
    <h3 class="mb-3">{{ __('My Expired Signals') }} <span class="badge badge-danger">{{$expiredSignals->count()}}</span></h3>
    <div class="card mb-4">
        <form method="POST" action="{{ route('signals.prolong') }}" class="card-body">
            @csrf
            <input type="hidden" name="prolong" value="1">
            <div class="row mb-2">
                <div class="col-md-8">
                    <b>{{ __('Name') }}</b>
                </div>
                <div class="col-md-3">
                    <b>{{ __('Expired Date') }}</b>
                </div>
                <div class="col-md-1"></div>
            </div>

            @foreach ($expiredSignals as $purchase)
            <div class="row mb-3 align-items-center">
                <div class="col-md-8 mb-2">
                    <input type="text" class="form-control" value="{{$purchase->signal->name}} - {{$purchase->signal->account->data->growth}}% dd-{{$purchase->signal->account->data->drawdown}}%" disabled>
                </div>
                <div class="col-md-3 mb-2">
                    <input type="text" class="form-control" value="{{ $purchase->expiredDate()->format('Y-m-d') }}" disabled>
                </div>
                <div class="col-md-1 mb-2">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck{{ $purchase->id }}" name="purchases[]" value="{{ $purchase->id }}">
                        <label class="custom-control-label" for="customCheck{{ $purchase->id }}"></label>
                    </div>
                </div>
            </div>
            @endforeach

            <div class="row align-items-center">
                <div class="col-md-6">
                    <button class="btn btn-primary" type="submit" name="submit" value="1" disabled>Prolong Signals</button>
                </div>
                <div class="col-md-6 text-right">
                    <div class=""><b>Total:</b> <span data-signals="total">0</span>$</div>
                </div>
            </div>
        </form>
    </div>
    @endif
</div>

resources/views/signals/top.blade.php
<div class="fx_row">
    @foreach($signals as $signal)
    <div class="fx_col">
        <div class="fx_card">
            <div class="fx_card-body fx_card-header">
                <h6 class="fx_name">{{ $signal->name }}</h6>
                <b>+{{ $signal->account->data->growth }}%</b>
            </div>
            <div class="fx_graph">
                <img src="{{$signal->account->chart(300, 2)}}" width="100%" alt="{{ $signal->name }}">
            </div>
            <a href="{{ route('signals.view', [$signal->id]) }}" class="fx_card-body">Copy</a>
        </div>
    </div>
    @endforeach
</div>