routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('referral');

Auth::routes(['verify' => true]);

Route::get('/api/top', 'ApiController@top')->name('api.top');
Route::post('/api/order', 'ApiController@order')->name('api.order');
Route::get('/api/account', 'ApiController@account')->name('api.account');

Route::get('/news', 'HomeController@news')->name('news');

Route::put('/home/update', 'HomeController@update')->middleware('auth')->name('profile.update');
Route::get('/code/{code}', 'HomeController@code')->name('profile.code');

Route::group(['middleware' => ['auth','verified']], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/reward', 'ForexController@reward')->name('reward');
    Route::get('/reward/{signal_id}', 'ForexController@reward')->name('reward_select');
    Route::get('/catalog', 'ForexController@catalog')->name('catalog');
    Route::post('/catalog/pay', 'ForexController@catalog_pay')->name('catalog.pay');
    Route::post('/catalog/calc', 'ForexController@catalog_calc')->name('catalog.calc');
    Route::post('/catalog/prolong', 'ForexController@catalog_prolong')->name('catalog.prolong');

    Route::get('/balance', 'ForexController@balance_history')->name('balance');

    Route::get('/withdraw', ['as' => 'withdraw', 'uses' => 'PaymentController@withdraw']);
    Route::post('/withdraw', ['as' => 'withdraw', 'uses' => 'PaymentController@withdraw']);
    Route::post('/payment', ['as' => 'payment', 'uses' => 'PaymentController@payWithpaypal']);
    Route::get('/payment/status',['as' => 'status', 'uses' => 'PaymentController@getPaymentStatus']);
    Route::get('/promo',['as' => 'promo', 'uses' => 'Admin\PromoController@apply', 'namespace' => 'Admin']);

    Route::get('/services', 'ForexController@services')->name('services');

    Route::get('/cart', 'ForexController@cart')->name('cart');
    Route::get('/cart_buy', 'ForexController@cart_buy')->name('cart_buy');
    Route::post('/cart/update', 'ForexController@cart_update')->name('cart_update');

    Route::get('/accounts/list', 'ForexController@accounts')->name('accounts.list');
    Route::get('/accounts/servers/{broker_id}', 'AccountsController@servers')->name('accounts.servers');
    Route::resource('accounts', 'AccountsController');
});

// Route::get('/promo', 'PromoController@apply')->name('promo');

Route::get('/signals/my', 'SignalsController@my')->name('signals.my');
Route::middleware('verified')->prefix('signals')->name('signals.')->group(function () {
    // Route::get('/my', 'SignalsController@my')->name('my');
    Route::get('create', 'SignalsController@create')->name('create');
    Route::post('store', 'SignalsController@store')->name('store');

    Route::get('/account', 'ForexController@signals_account')->name('account');
    Route::delete('', 'ForexController@signals_delete')->name('delete');
    Route::post('/activate', 'ForexController@signals_activate')->name('activate');
    Route::post('/prolong', 'ForexController@signals_prolong')->name('prolong');
});
Route::get('/signals/{id}', 'SignalsController@view')->name('signals.view');

Route::middleware('auth')->group(function () {
    Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('perm:manage-users')->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('signals', 'SignalsController');
        Route::resource('withdraw', 'WithdrawController');
        Route::resource('payments', 'PaymentsController');
        Route::resource('masters', 'MastersController');
        Route::resource('promo', 'PromoController');
        Route::resource('news', 'NewsController');
        Route::get('settings', 'SettingsController@index')->name('settings');
        Route::post('settings', 'SettingsController@index');
        Route::post('settings/upload', 'SettingsController@upload');

        Route::get('tasks', 'TasksController@index')->name('tasks.index');
        Route::delete('tasks/{account_id}', 'TasksController@destroy')->name('tasks.destroy');
    });
});

Route::get('/cron', 'CronController@fx')->name('cron');
Route::get('/cron/notify', 'CronController@notify')->name('notify');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="min-percent" content="{{ env('MIN_PERCENT') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timeago/1.4.3/jquery.timeago.min.js"></script>
    <script type="text/javascript">
        var $j = jQuery.noConflict();
        $j(document).ready(function () {
            console.log($j("abbr.timeago").timeago());
        });
    </script>
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/9270e8f050.js" crossorigin="anonymous"></script>

    <script type="text/javascript">
        var addAccountRefresh = false;
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @can('manage-users')
                        <li class="nav-item {{ (Request::segment(1) == 'admin' && Request::segment(2) == 'signals') ? 'active' : '' }}">
                            <a href="{{ route('admin.signals.index') }}" class="nav-link">Signals</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdownMoney" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ __('Money') }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMoney">
                                <a href="{{ route('admin.withdraw.index') }}" class="dropdown-item">Withdraw</a>
                                <a href="{{ route('admin.payments.index') }}" class="dropdown-item">Payments</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdownMoney" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ __('Objects') }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMoney">
                                <a href="{{ route('admin.users.index') }}" class="dropdown-item">Users</a>
                                <a href="{{ route('admin.news.index') }}" class="dropdown-item">News</a>
                                <a href="{{ route('cron') }}" class="dropdown-item">Sync Myfxbook</a>
                            </div>
                        </li>
                        <li class="nav-item {{ (Request::segment(1) == 'admin' && Request::segment(2) == 'promo') ? 'active' : '' }}">
                            <a href="{{ route('admin.promo.index') }}" class="nav-link">Promo</a>
                        </li>
                        @if(Auth::user()->tasks())
                        <li class="nav-item {{ (Request::segment(1) == 'admin' && Request::segment(2) == 'tasks') ? 'active' : '' }}">
                            <a href="{{ route('admin.tasks.index') }}" class="nav-link">Tasks  <span class="badge badge-primary ml-1" style="top: -2px;position: relative">{{ Auth::user()->tasks() }}</span></a>
                        </li>
                        @endif
                        <li class="nav-item {{ (Request::segment(1) == 'admin' && Request::segment(2) == 'settings') ? 'active' : '' }}">
                            <a href="{{ route('admin.settings') }}" class="nav-link">Settings</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a href="{{ route('admin.masters.index') }}" class="nav-link">Masters</a>
                        </li> -->
                        @endcan
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item {{ Request::segment(1) == 'login' ? 'active' : '' }}">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item {{ Request::segment(1) == 'register' ? 'active' : '' }}">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            @if ( Auth::user()->getServicesCount() )
                                <li class="nav-item {{ Request::segment(1) == 'services' ? 'active' : '' }}">
                                    <a href="{{ route('services') }}" class="nav-link text-primary">{{ __('Services') }} <span class="badge badge-danger ml-1" style="top: -2px;position: relative">{{ Auth::user()->getServicesCount() }}</span></a>
                                </li>
                            @endif
                            @if ( Session::has('cart') )
                                @if ( count(Session::get('cart')->items) )
                                <li class="nav-item {{ Request::segment(1) == 'cart' ? 'active' : '' }}">
                                    <a href="{{ route('cart') }}" class="nav-link text-primary">{{ __('Cart') }} <span class="badge badge-primary ml-1" style="top: -2px;position: relative">{{ count(Session::get('cart')->items) }}</span></a>
                                </li>
                                @endif
                            @endif
                            <li class="nav-item {{ Request::segment(1) == 'catalog' ? 'active' : '' }}">
                                <a href="{{ route('catalog') }}" class="nav-link">{{ __('Catalog') }}</a>
                            </li>
                            <li class="nav-item {{ Request::segment(1) == 'signals' ? 'active' : '' }}">
                                <a href="{{ route('signals.my') }}" class="nav-link">{{ __('My Signals') }}</a>
                            </li>
                            <li class="nav-item {{ Request::segment(1) == 'accounts' ? 'active' : '' }}">
                                <a href="{{ route('accounts.list') }}" class="nav-link">{{ __('My Accounts') }}</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a href="#" data-toggle="modal" data-target="#exampleModal" class="dropdown-item d-flex align-items-center" href="{{ route('home') }}">{{ __('Balance') }}: <b class="d-block ml-1 mr-2">$<span data-user="balance">{{ Auth::user()->balance }}</span></b> <span class="badge badge-primary"><i class="fa fa-plus"></i></span></a>
                                    <a class="dropdown-item" href="{{ route('home') }}">{{ __('Profile') }}</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header pb-2 pt-3">
                <h5 class="modal-title" id="exampleModalLabel">{{ __('Balance Replenishment') }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                  <form class="row" action="{{ route('payment') }}" method="post">
                      @csrf
                      <div class="col-md-8">
                          <div class="input-group">
                            <div class="input-group-prepend">
                              <div class="input-group-text">$</div>
                            </div>
                            <input type="text" name="amountToBePaid" class="form-control" id="sum" value="100" placeholder="Amount">
                          </div>
                      </div>
                      <div class="col-md-4">
                          <button type="submit" class="btn btn-primary btn-block">{{ __('Replenish') }}</button>
                      </div>
                  </form>
              </div>
            </div>
          </div>
        </div>

        <div class="container mt-5">
            <div class="row">
                <div class="col-md-12">
                    @if(Auth::check())
                        @if(Auth::user()->rewards->count())
                            <div class="alert alert-success">
                                <strong>{{ __('Congratulations!') }}</strong> {{ __('You have :count reward(s)', ['count' => Auth::user()->rewards->count()]) }}
                                <a href="{{ route('reward') }}" class="float-right alert-link">
                                    {{ __('Select') }}
                                </a>
                            </div>
                        @endif
                    @endif
                </div>
            </div>
        </div>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/cabinet.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>

    @if (Route::has('login'))
        <div class="top-right links">
            @auth
                <a href="{{ url('/home') }}">Home</a>
            @else
                <a href="{{ route('login') }}">Login</a>

                @if (Route::has('register'))
                    <a href="{{ route('register') }}">Register</a>
                @endif
            @endauth
        </div>
    @endif

    @yield('content')

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>